config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    get 'flats/:id', to: 'flats#show', as: :flat
    root to: 'flats#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats, only: [:index, :show]

  def index;end

  def show
    @flat = @flats.find do |flat|
      flat["id"] == params[:id].to_i
    end
  end

  private

  def set_flats
    flats_serialized = open('https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json').read
    @flats = JSON.parse(flats_serialized)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <% @flats.each do |flat| %>
    <li><%= link_to flat["name"], flat_path(flat["id"]) %></li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<p>Price: <%= @flat["price"] %> (<%= @flat["priceCurrency"] %>)</p>
<%= link_to "< Go Home", root_path, class: "home_btn" %>
<img src="<%= @flat["imageUrl"] %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🏚 Simple Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>